{"author":{"id":"3db78f068ad868a19394cf4100945310e3f47c87633ffb7b8547ba51bedaf94a"},"ops":[{"type":1,"timestamp":1545317948,"nonce":"WNztLf7Nlca7mGP0rbF686Ia6IE=","metadata":{"github-id":"MDU6SXNzdWUzOTMwODIxOTM=","github-url":"https://github.com/svpcom/wfb-ng/issues/24","origin":"github"},"title":"Failed to build wifibroadcast-18.12","message":"```\npi@raspberrypi:~/wifibroadcast $ make\nPYTHONPATH=`pwd` trial telemetry.tests\ntelemetry\n  tests\n    test_proxy ...                                                      [ERROR]\n\n===============================================================================\n[ERROR]\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/twisted/trial/runner.py\", line 498, in loadPackage\n    module = modinfo.load()\n  File \"/usr/lib/python2.7/dist-packages/twisted/python/modules.py\", line 383, in load\n    return self.pathEntry.pythonPath.moduleLoader(self.name)\n  File \"/usr/lib/python2.7/dist-packages/twisted/python/reflect.py\", line 303, in namedAny\n    topLevelPackage = _importAndCheckStack(trialname)\n  File \"/usr/lib/python2.7/dist-packages/twisted/python/reflect.py\", line 250, in _importAndCheckStack\n    reraise(excValue, excTraceback)\n  File \"/home/pi/wifibroadcast/telemetry/tests/test_proxy.py\", line 8, in \u003cmodule\u003e\n    from telemetry.proxy import UDPProxyProtocol\n  File \"/home/pi/wifibroadcast/telemetry/proxy.py\", line 21, in \u003cmodule\u003e\n    import mavlink\n  File \"/home/pi/wifibroadcast/telemetry/mavlink.py\", line 9, in \u003cmodule\u003e\n    from builtins import range\nexceptions.ImportError: No module named builtins\n\ntelemetry.tests.test_proxy\n-------------------------------------------------------------------------------\nRan 1 tests in 0.023s\n\nFAILED (errors=1)\nMakefile:43: recipe for target 'test' failed\nmake: *** [test] Error 1\n```\n\nI am new to python, so I donâ€™t know what to do with it.\nC ++ part of the project is building fine.","files":null}]}