{"author":{"id":"c0aec0e9db69e0cb495b53bfaa4b5d5ec2018ebd15ca1e4c55e9334cba2de8ad"},"ops":[{"type":6,"timestamp":1621995819,"nonce":"ZxRqUpxbmH9cQz5f3I80wPHfFDs=","metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdElzc3VlRWRpdDo1NDUwODE2MjA="},"target":"2dfb1d15a9c82f32e559be63c3635dad02e255f2d524e6fc8e4377a7e4f9d5f5","message":"**Describe the bug**\nInstallation fails on ubuntu Focal (20.04).\n\n**To Reproduce**\nSteps to reproduce the behavior:\nInstallation steps until executing make deb.\n\n**Screenshots**\n![image](https://user-images.githubusercontent.com/41023326/119593331-366dee80-bdb0-11eb-812e-c7431e2f3545.png)\n\n\n**Your setup (please complete the following information):**\n - Ubuntu 20.04\n - Hardware: Rpi 4","files":null},{"type":3,"timestamp":1621995931,"nonce":"bO//O7VzZ/KeSaY5WtL3nZA50rE=","metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDg0ODQwNzMwMA==","github-url":"https://github.com/svpcom/wfb-ng/issues/136#issuecomment-848407300"},"message":"Seems the issue is in wifibroadcast/version.py\n\nI don't have python2 installed and the env in version.py is /usr/bin/env python.\n\nChanging it to /usr/bin/env python3 solved the issue.\n\nLeaving here for documentation purposes.","files":null},{"type":2,"timestamp":1621996126,"nonce":"XwF556IUG0yNWVAbCT8K+kUOnEQ=","metadata":{"github-id":"MDE3OlJlbmFtZWRUaXRsZUV2ZW50NDc5NjMyMzUxMA=="},"title":"Installation fails on ubuntu 20.04 with python3","was":"Installation fails on ubuntu 20.04 with python3"},{"type":4,"timestamp":1621996132,"nonce":"HXYkgodTRXkmo+8J7wExhclOD3E=","metadata":{"github-id":"MDExOkNsb3NlZEV2ZW50NDc5NjMyMzc0MA=="},"status":2}]}