{"author":{"id":"ab876037f9d0d044ec302b26577879cdba205bcd6481d508389ce8aae6090a69"},"ops":[{"type":3,"timestamp":1662059437,"nonce":"9Nrh++D+BDuWuBByJD9tVVX1xpc=","metadata":{"github-id":"IC_kwDOBLCY8M5Jl7Br","github-url":"https://github.com/svpcom/wfb-ng/issues/246#issuecomment-1234677867"},"message":"One step further! Now I have this problem\n\n`Traceback (most recent call last):\n  File \"./setup.py\", line 62, in \u003cmodule\u003e\n    setup(\n  File \"/home/john/src/wifibroadcast/env/lib/python3.8/site-packages/setuptools/__init__.py\", line 87, in setup\n    return distutils.core.setup(**attrs)\n  File \"/home/john/src/wifibroadcast/env/lib/python3.8/site-packages/setuptools/_distutils/core.py\", line 185, in setup\n    return run_commands(dist)\n  File \"/home/john/src/wifibroadcast/env/lib/python3.8/site-packages/setuptools/_distutils/core.py\", line 201, in run_commands\n    dist.run_commands()\n  File \"/home/john/src/wifibroadcast/env/lib/python3.8/site-packages/setuptools/_distutils/dist.py\", line 973, in run_commands\n    self.run_command(cmd)\n  File \"/home/john/src/wifibroadcast/env/lib/python3.8/site-packages/setuptools/dist.py\", line 1217, in run_command\n    super().run_command(command)\n  File \"/home/john/src/wifibroadcast/env/lib/python3.8/site-packages/setuptools/_distutils/dist.py\", line 992, in run_command\n    cmd_obj.run()\n  File \"/home/john/src/wifibroadcast/env/lib/python3.8/site-packages/stdeb/command/bdist_deb.py\", line 34, in run\n    self.run_command('sdist_dsc')\n  File \"/home/john/src/wifibroadcast/env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py\", line 319, in run_command\n    self.distribution.run_command(command)\n  File \"/home/john/src/wifibroadcast/env/lib/python3.8/site-packages/setuptools/dist.py\", line 1217, in run_command\n    super().run_command(command)\n  File \"/home/john/src/wifibroadcast/env/lib/python3.8/site-packages/setuptools/_distutils/dist.py\", line 992, in run_command\n    cmd_obj.run()\n  File \"/home/john/src/wifibroadcast/env/lib/python3.8/site-packages/stdeb/command/sdist_dsc.py\", line 30, in run\n    debinfo = self.get_debinfo()\n  File \"/home/john/src/wifibroadcast/env/lib/python3.8/site-packages/stdeb/command/common.py\", line 197, in get_debinfo\n    debinfo = DebianInfo(\n  File \"/home/john/src/wifibroadcast/env/lib/python3.8/site-packages/stdeb/util.py\", line 934, in __init__\n    for line in long_description.split('\\n'):\nAttributeError: 'NoneType' object has no attribute 'split' `","files":null}]}