{"author":{"id":"f6e2c84cbd41daecf4582d969b556a96eb202b5bed142fd85d6e07732fc4fe19"},"ops":[{"type":3,"timestamp":1713563900,"nonce":"5h/B+3ory42nlWWGw3GgWn5HPqg=","metadata":{"github-id":"IC_kwDOBLCY8M57OPci","github-url":"https://github.com/svpcom/wfb-ng/issues/333#issuecomment-2067330850"},"message":"\u003e It seems that something broken in your python setup. Why it adds `local` to the path? \n\nAs `make deb` can't find the python, so I tried to fix it locally.\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ git log -n 1\ncommit 24722e9b8b0dba0f202e064c3366715e3da5f052 (HEAD -\u003e lida2003-test)\nAuthor: Daniel Li \u003clida_mail@163.com\u003e\nDate:   Sat Apr 20 05:31:35 2024 +0800\n\n    Fix for Jetson Orin Jimmy(22.04) python path\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ git show 24722e9b8b0dba0f202e064c3366715e3da5f052\ncommit 24722e9b8b0dba0f202e064c3366715e3da5f052 (HEAD -\u003e lida2003-test)\nAuthor: Daniel Li \u003clida_mail@163.com\u003e\nDate:   Sat Apr 20 05:31:35 2024 +0800\n\n    Fix for Jetson Orin Jimmy(22.04) python path\n\ndiff --git a/Makefile b/Makefile\nindex 82b9496..7c3e6ad 100644\n--- a/Makefile\n+++ b/Makefile\n@@ -15,7 +15,7 @@ all: all_bin gs.key test\n\n $(ENV):\n        virtualenv --python=$(PYTHON) $(ENV)\n-       $(ENV)/bin/pip install --upgrade pip setuptools stdeb\n+       $(ENV)/local/bin/pip install --upgrade pip setuptools stdeb\n\n all_bin: wfb_rx wfb_tx wfb_keygen\n\n@@ -47,7 +47,7 @@ rpm:  all_bin $(ENV)\n\n deb:  all_bin $(ENV)\n        rm -rf deb_dist\n-       $(ENV)/bin/python ./setup.py --command-packages=stdeb.command bdist_deb\n+       $(ENV)/local/bin/python ./setup.py --command-packages=stdeb bdist_deb\n        rm -rf wfb_ng.egg-info/ wfb-ng-$(VERSION).tar.gz\n\n bdist: all_bin\n```\n\n\n\u003e Try to replace virtualenv to venv.\n\u003e I.e instead of `virtualenv --python=/usr/bin/python3 /home/daniel/wfb/wfb-ng/env` run `/usr/bin/python3 -m venv /home/daniel/wfb/wfb-ng/env`\n\nI'm NOT sure what's going on here. I follow the guide `apt install python3.10-venv` and then `make clean` `make env` `make deb`\nThere is no luck on master or my test branch.\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ /usr/bin/python3 -m venv /home/daniel/wfb/wfb-ng/env\nThe virtual environment was not created successfully because ensurepip is not\navailable.  On Debian/Ubuntu systems, you need to install the python3-venv\npackage using the following command.\n\n    apt install python3.10-venv\n\nYou may need to use sudo with that command.  After installing the python3-venv\npackage, recreate your virtual environment.\n\nFailing command: /home/daniel/wfb/wfb-ng/env/bin/python3\n```","files":null},{"type":6,"timestamp":1713563939,"nonce":"JJYw+LUmdXq6blX0GeDRMysyXaM=","metadata":{"github-id":"UCE_lALOBLCY8M57OPcizkSe6V4"},"target":"2a2729c041f523a5d71c8f45f6fbf6b2cfd4e8b06ab76b0f4400eb875cedda6c","message":"\u003e It seems that something broken in your python setup. Why it adds `local` to the path? \n\nAs `make deb` can't find the python, so I tried to fix it locally.\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ git show 24722e9b8b0dba0f202e064c3366715e3da5f052\ncommit 24722e9b8b0dba0f202e064c3366715e3da5f052 (HEAD -\u003e lida2003-test)\nAuthor: Daniel Li \u003clida_mail@163.com\u003e\nDate:   Sat Apr 20 05:31:35 2024 +0800\n\n    Fix for Jetson Orin Jimmy(22.04) python path\n\ndiff --git a/Makefile b/Makefile\nindex 82b9496..7c3e6ad 100644\n--- a/Makefile\n+++ b/Makefile\n@@ -15,7 +15,7 @@ all: all_bin gs.key test\n\n $(ENV):\n        virtualenv --python=$(PYTHON) $(ENV)\n-       $(ENV)/bin/pip install --upgrade pip setuptools stdeb\n+       $(ENV)/local/bin/pip install --upgrade pip setuptools stdeb\n\n all_bin: wfb_rx wfb_tx wfb_keygen\n\n@@ -47,7 +47,7 @@ rpm:  all_bin $(ENV)\n\n deb:  all_bin $(ENV)\n        rm -rf deb_dist\n-       $(ENV)/bin/python ./setup.py --command-packages=stdeb.command bdist_deb\n+       $(ENV)/local/bin/python ./setup.py --command-packages=stdeb bdist_deb\n        rm -rf wfb_ng.egg-info/ wfb-ng-$(VERSION).tar.gz\n\n bdist: all_bin\n```\n\n\n\u003e Try to replace virtualenv to venv.\n\u003e I.e instead of `virtualenv --python=/usr/bin/python3 /home/daniel/wfb/wfb-ng/env` run `/usr/bin/python3 -m venv /home/daniel/wfb/wfb-ng/env`\n\nI'm NOT sure what's going on here. I follow the guide `apt install python3.10-venv` and then `make clean` `make env` `make deb`\nThere is no luck on master or my test branch.\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ /usr/bin/python3 -m venv /home/daniel/wfb/wfb-ng/env\nThe virtual environment was not created successfully because ensurepip is not\navailable.  On Debian/Ubuntu systems, you need to install the python3-venv\npackage using the following command.\n\n    apt install python3.10-venv\n\nYou may need to use sudo with that command.  After installing the python3-venv\npackage, recreate your virtual environment.\n\nFailing command: /home/daniel/wfb/wfb-ng/env/bin/python3\n```","files":null},{"type":6,"timestamp":1713564018,"nonce":"a3zL7hqI7/6ToRjVC8SEthcktZo=","metadata":{"github-id":"UCE_lALOBLCY8M57OPcizkSe7as"},"target":"2a2729c041f523a5d71c8f45f6fbf6b2cfd4e8b06ab76b0f4400eb875cedda6c","message":"\u003e It seems that something broken in your python setup. Why it adds `local` to the path? \n\nAs `make deb` can't find the python, so I tried to fix it locally.\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ git show 24722e9b8b0dba0f202e064c3366715e3da5f052\ncommit 24722e9b8b0dba0f202e064c3366715e3da5f052 (HEAD -\u003e lida2003-test)\nAuthor: Daniel Li \u003clida_mail@163.com\u003e\nDate:   Sat Apr 20 05:31:35 2024 +0800\n\n    Fix for Jetson Orin Jimmy(22.04) python path\n\ndiff --git a/Makefile b/Makefile\nindex 82b9496..7c3e6ad 100644\n--- a/Makefile\n+++ b/Makefile\n@@ -15,7 +15,7 @@ all: all_bin gs.key test\n\n $(ENV):\n        virtualenv --python=$(PYTHON) $(ENV)\n-       $(ENV)/bin/pip install --upgrade pip setuptools stdeb\n+       $(ENV)/local/bin/pip install --upgrade pip setuptools stdeb\n\n all_bin: wfb_rx wfb_tx wfb_keygen\n\n@@ -47,7 +47,7 @@ rpm:  all_bin $(ENV)\n\n deb:  all_bin $(ENV)\n        rm -rf deb_dist\n-       $(ENV)/bin/python ./setup.py --command-packages=stdeb.command bdist_deb\n+       $(ENV)/local/bin/python ./setup.py --command-packages=stdeb bdist_deb\n        rm -rf wfb_ng.egg-info/ wfb-ng-$(VERSION).tar.gz\n\n bdist: all_bin\n```\n\n\n\u003e Try to replace virtualenv to venv.\n\u003e I.e instead of `virtualenv --python=/usr/bin/python3 /home/daniel/wfb/wfb-ng/env` run `/usr/bin/python3 -m venv /home/daniel/wfb/wfb-ng/env`\n\nI'm NOT sure what's going on here. I follow the guide `apt install python3.10-venv` and then `make clean` `make env` `make deb`\nThere is no luck on master or my test branch.\n\n```\ndaniel@daniel-nvidia:~/wfb/wfb-ng$ /usr/bin/python3 -m venv /home/daniel/wfb/wfb-ng/env\nThe virtual environment was not created successfully because ensurepip is not\navailable.  On Debian/Ubuntu systems, you need to install the python3-venv\npackage using the following command.\n\n    apt install python3.10-venv\n\nYou may need to use sudo with that command.  After installing the python3-venv\npackage, recreate your virtual environment.\n\nFailing command: /home/daniel/wfb/wfb-ng/env/bin/python3\n```\n\n\n--- EDIT\n\n```\n$ virtualenv --python=/usr/bin/python3 /home/daniel/wfb/wfb-ng/env\ncreated virtual environment CPython3.10.12.final.0-64 in 238ms\n  creator CPython3Posix(dest=/home/daniel/wfb/wfb-ng/env, clear=False, no_vcs_ignore=False, global=False)\n  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/daniel/.local/share/virtualenv)\n    added seed packages: pip==22.0.2, setuptools==59.6.0, wheel==0.37.1\n  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator\n```","files":null}]}